In [1]:
import pandas as pd

In [10]:
data = pd.read_csv('./okcupid_profiles.csv')

In [11]:
data

,age,status,sex,orientation,body_type,diet,drinks,drugs,education,ethnicity,...,essay0,essay1,essay2,essay3,essay4,essay5,essay6,essay7,essay8,essay9
0,22,single,m,straight,a little extra,strictly anything,socially,never,working on college/university,"asian, white",...,about me: i would love to think that i was so...,currently working as an international agent fo...,making people laugh. ranting about a good salt...,"the way i look. i am a six foot half asian, ha...","books: absurdistan, the republic, of mice and ...",food. water. cell phone. shelter.,duality and humorous things,trying to find someone to hang out with. i am ...,i am new to california and looking for someone...,you want to be swept off your feet! you are ti...
1,35,single,m,straight,average,mostly other,often,sometimes,working on space camp,white,...,i am a chef: this is what that means. 1. i am ...,dedicating everyday to being an unbelievable b...,being silly. having ridiculous amonts of fun w...,NaN,i am die hard christopher moore fan. i don't r...,delicious porkness in all of its glories. my b...,NaN,NaN,i am very open and will share just about anyth...,NaN
2,38,available,m,straight,thin,anything,socially,NaN,graduated from masters program,NaN,...,"i'm not ashamed of much, but writing public te...","i make nerdy software for musicians, artists, ...",improvising in different contexts. alternating...,my large jaw and large glasses are the physica...,okay this is where the cultural matrix gets so...,movement conversation creation contemplation t...,NaN,viewing. listening. dancing. talking. drinking...,"when i was five years old, i was known as ""the...","you are bright, open, intense, silly, ironic, ..."
3,23,single,m,straight,thin,vegetarian,socially,NaN,working on college/university,white,...,i work in a library and go to school. . .,reading things written by old dead people,playing synthesizers and organizing books acco...,socially awkward but i do my best,"bataille, celine, beckett. . . lynch, jarmusch...",NaN,cats and german philosophy,NaN,NaN,you feel so inclined.
4,29,single,m,straight,athletic,NaN,socially,never,graduated from college/university,"asian, black, other",...,hey how's it going? currently vague on the pro...,work work work work + play,creating imagery to look at: http://bagsbrown....,i smile a lot and my inquisitive nature,"music: bands, rappers, musicians at the moment...",NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59941,59,single,f,straight,NaN,NaN,socially,never,graduated from college/university,NaN,...,"vibrant, expressive, caring optimist. i love b...",the happiest times have been when life came to...,i make an outstanding osso bucco. i am also ve...,"i am told that people notice my smile, eyes an...",i am an avid movie watcher and follow the broa...,"my family, my dog, italy, words and music!",writing my book.,"running with my dog, finishing up the work wee...",i have a dream to sing at the alconquin in nyc...,you are seeking a long term connection of shar...
59942,24,single,m,straight,fit,mostly anything,often,sometimes,working on college/university,"white, other",...,i'm nick. i never know what to write about mys...,currently finishing school for film production...,"filmmaking, photography, graphic design, web d...","dude, i don't know.","movies: hook (the greatest adventure ever!), g...",iphone contact lenses headphones camera tv rem...,i do most of my thinking on the bus to/from wo...,"bringin' home bacon, or drinking and shakin'!",when i was 18 i got a tattoo of waldo somewher...,meh if you made it this far you might as well.
59943,42,single,m,straight,average,mostly anything,not at all,never,graduated from masters program,asian,...,"hello! i enjoy traveling, watching movies, and...","i'm a civil engineer, who enjoys helping the c...",- looking at things objectively - getting thin...,i'm quiet until i get used to the environment ...,"last book: ""game change"". movies: bourne serie...",- iphone - friends and family - internet - bay...,"aside from work, how to improve my home.",out enjoying friendly conversation over dinner.,please let me think about this more.,we have similar interests.
59944,27,single,m,straight,athletic,mostly anything,socially,often,working on college/university,"asian, black",...,"""all i have in this world are my balls and my ...","following my dreams... ""you got a dream... you...",listening,it used to be the hair until i mowed it off bu...,where to begin musically: right now i listen t...,"music, family, friends, a basketball, hoop, so...",what can i do to make someone chuckle....,what i would do on any other day. everydays a ...,i like walking around in other people's house ...,you are interested and interesting...
59945,39,single,m,gay,average,NaN,socially,NaN,graduated from masters program,white,...,"is it odd that having a little ""enemy"" status ...",i work with elderly people (psychotherapy and ...,i'm a great bullshitter. i don't know what it ...,"either that i am funny/sarcastic, or that i am...","i just read the help by kathryn stockett, sooo...",1. family & friends & other humans - interacti...,"sex, myself, other people, how amazing everyth...","out at happy hour with my friends, running int...",i wish i could cry like holly hunter in broadc...,"if you have a back-bone, an opinion, a sense o..."

Data Analysis of users' profiles on dating app OkCupid

In [13]:
data.head(5)

,age,status,sex,orientation,body_type,diet,drinks,drugs,education,ethnicity,...,essay0,essay1,essay2,essay3,essay4,essay5,essay6,essay7,essay8,essay9
0,22,single,m,straight,a little extra,strictly anything,socially,never,working on college/university,"asian, white",...,about me: i would love to think that i was so...,currently working as an international agent fo...,making people laugh. ranting about a good salt...,"the way i look. i am a six foot half asian, ha...","books: absurdistan, the republic, of mice and ...",food. water. cell phone. shelter.,duality and humorous things,trying to find someone to hang out with. i am ...,i am new to california and looking for someone...,you want to be swept off your feet! you are ti...
1,35,single,m,straight,average,mostly other,often,sometimes,working on space camp,white,...,i am a chef: this is what that means. 1. i am ...,dedicating everyday to being an unbelievable b...,being silly. having ridiculous amonts of fun w...,NaN,i am die hard christopher moore fan. i don't r...,delicious porkness in all of its glories. my b...,NaN,NaN,i am very open and will share just about anyth...,NaN
2,38,available,m,straight,thin,anything,socially,NaN,graduated from masters program,NaN,...,"i'm not ashamed of much, but writing public te...","i make nerdy software for musicians, artists, ...",improvising in different contexts. alternating...,my large jaw and large glasses are the physica...,okay this is where the cultural matrix gets so...,movement conversation creation contemplation t...,NaN,viewing. listening. dancing. talking. drinking...,"when i was five years old, i was known as ""the...","you are bright, open, intense, silly, ironic, ..."
3,23,single,m,straight,thin,vegetarian,socially,NaN,working on college/university,white,...,i work in a library and go to school. . .,reading things written by old dead people,playing synthesizers and organizing books acco...,socially awkward but i do my best,"bataille, celine, beckett. . . lynch, jarmusch...",NaN,cats and german philosophy,NaN,NaN,you feel so inclined.
4,29,single,m,straight,athletic,NaN,socially,never,graduated from college/university,"asian, black, other",...,hey how's it going? currently vague on the pro...,work work work work + play,creating imagery to look at: http://bagsbrown....,i smile a lot and my inquisitive nature,"music: bands, rappers, musicians at the moment...",NaN,NaN,NaN,NaN,NaN

In [30]:
data.query('sex == "f"')

,age,status,sex,orientation,body_type,diet,drinks,drugs,education,ethnicity,...,essay0,essay1,essay2,essay3,essay4,essay5,essay6,essay7,essay8,essay9
6,32,single,f,straight,fit,strictly anything,socially,never,graduated from college/university,"white, other",...,life is about the little things. i love to lau...,digging up buried treasure,frolicking witty banter using my camera to ext...,i am the last unicorn,i like books. ones with pictures. reading them...,laughter amazing people in my life color curio...,synchronicity there is this whole other realm...,plotting to take over the world with my army o...,my typical friday night,NaN
7,31,single,f,straight,average,mostly anything,socially,never,graduated from college/university,white,...,NaN,"writing. meeting new people, spending time wit...","remembering people's birthdays, sending cards,...",i'm rather approachable (a byproduct of being ...,"i like: alphabetized lists, aquariums, autobio...","friends, family, notebook/pen, books, music, t...",things that amuse and inspire me,out and about or relaxing at home with a good ...,NaN,NaN
8,24,single,f,straight,NaN,strictly anything,socially,NaN,graduated from college/university,white,...,NaN,"oh goodness. at the moment i have 4 jobs, so i...",NaN,i'm freakishly blonde and have the same name a...,i am always willing to try new foods and am no...,sports/my softball glove coffee. because nobod...,NaN,"in or out... drinking with friends, maybe a ba...",potential friends/lovers/people who come in co...,http://www.youtube.com/watch?v=4dxbwzuwsxk let...
13,30,single,f,straight,skinny,mostly anything,socially,never,graduated from high school,white,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,29,single,f,straight,thin,mostly anything,socially,never,working on college/university,"hispanic / latin, white",...,NaN,i have an awesome career working as a senior m...,listening. helping others. being patient. comm...,"well, i get the most compliments on my butt, s...",books: my all-time favorite book is george orw...,1. my family 2. italian or mexican food 3. my ...,"to be honest, i spend way too much time thinki...",unwinding from my work week. hanging out with ...,"hmmm...not sure if i want to admit this, but p...",...you genuinely think we'd be a good match.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59934,43,single,f,straight,average,anything,socially,NaN,graduated from masters program,white,...,i'm an east coast/west coast hybrid who's live...,"starting a business; raising a wonderful, sill...","finding joy in simple things, getting lost, ma...",i've been told my eyes but also that i smile a...,i love reading but these days more of my time ...,"1. water....in the ocean, lake, bathtub 2. sen...","-how to be a better parent, friend, daughter, ...","home with my son, playing with legos, wrestlin...","i'm recently divorced, but have been separated...",-you are intrigued by any of the above -you ar...
59935,33,single,f,straight,curvy,anything,socially,never,NaN,white,...,i am a mom first and foremost. currently separ...,i currently work at safeway. hopefully not for...,a lot of things...,my eyes and then the fact that i am pretty str...,i love to read and so i do not have an absolut...,my kids my ipod/iphone water my car my mac my ...,everything i have and want to do!,"either working, hang in' with my kids or out h...",hahaha! i'm not telling...yet.,"you kept reading after currently separated, ar..."
59936,25,single,f,straight,average,mostly anything,socially,never,graduated from college/university,asian,...,NaN,NaN,NaN,my infectious laugh :),NaN,NaN,NaN,NaN,NaN,NaN
59940,31,single,f,straight,NaN,NaN,socially,never,working on masters program,middle eastern,...,"real deal: i am sensitive (sorry, tears includ...",right now...watching 'celebrity rehab' and com...,eating chocolate and doing pilates (usually no...,my hair? eyes? height? curves? dk....my caring...,"too many to name ... -a new earth, kite runner...",1. pilates 2. solo relaxation time (with or wi...,how i am gonna answer this question! ...existe...,doing the obvious two things everyone is doing...,--is that i sometimes watch reality tv (even t...,--if you have the courage to tell me why you c...
59941,59,single,f,straight,NaN,NaN,socially,never,graduated from college/university,NaN,...,"vibrant, expressive, caring optimist. i love b...",the happiest times have been when life came to...,i make an outstanding osso bucco. i am also ve...,"i am told that people notice my smile, eyes an...",i am an avid movie watcher and follow the broa...,"my family, my dog, italy, words and music!",writing my book.,"running with my dog, finishing up the work wee...",i have a dream to sing at the alconquin in nyc...,you are seeking a long term connection of shar...

In [34]:
data.query('sex == "f"' and 'status == "single"').count()

age            55697
status         55697
sex            55697
orientation    55697
body_type      51057
diet           33420
drinks         52850
drugs          42697
education      49510
ethnicity      50537
height         55694
income         55697
job            48033
last_online    55697
location       55697
offspring      22858
pets           36799
religion       36471
sign           45313
smokes         50459
speaks         55650
essay0         50466
essay1         48546
essay2         46568
essay3         44866
essay4         45743
essay5         45523
essay6         42664
essay7         44003
essay8         37448
essay9         43687
dtype: int64

Looking for missing values

In [16]:
data.isna().sum()

age                0
status             0
sex                0
orientation        0
body_type       5296
diet           24395
drinks          2985
drugs          14080
education       6628
ethnicity       5680
height             3
income             0
job             8198
last_online        0
location           0
offspring      35561
pets           19921
religion       20226
sign           11056
smokes          5512
speaks            50
essay0          5488
essay1          7572
essay2          9638
essay3         11476
essay4         10537
essay5         10850
essay6         13771
essay7         12451
essay8         19225
essay9         12603
dtype: int64

In [35]:
data.query('sex == "f"' and 'status == "single"').mean()

/var/folders/n2/w8qr7mt13pz1cdd560k6hl8h0000gn/T/ipykernel_1184/3927967778.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  data.query('sex == "f"' and 'status == "single"').mean()

age          32.371223
height       68.290714
income    19605.809433
dtype: float64

In [39]:
data.query('sex == "f"' and 'status == "available"').mean()

/var/folders/n2/w8qr7mt13pz1cdd560k6hl8h0000gn/T/ipykernel_1184/2551827234.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  data.query('sex == "f"' and 'status == "available"').mean()

age          33.869169
height       68.838606
income    27859.840751
dtype: float64

Single and available female users have quite a large gap in terms of average income

In [44]:
data.describe()

                age        height          income
count  59946.000000  59943.000000    59946.000000
mean      32.340290     68.295281    20033.222534
std        9.452779      3.994803    97346.192104
min       18.000000      1.000000       -1.000000
25%       26.000000     66.000000       -1.000000
50%       30.000000     68.000000       -1.000000
75%       37.000000     71.000000       -1.000000
max      110.000000     95.000000  1000000.000000

On average the age of a user of the app is 32 years old, with an income around 20.000$ (but stardard deviation is high, so it's difficult to say)

In [45]:
data.corr().style.background_gradient()

No relevant correlation between age, height and income

In [46]:
data.query('age>= "30"' and 'sex == "m"')['status == "available"'].count()

KeyError: 'status == "available"'

I wanted to count the male users with an age >= 30 and still single, but didn't manage

In [43]:
age = pd.cut(data['age'], [0, 10, 30, 60, 80])
result = data.pivot_table(index = ['sex', age], columns = ['income'])
print(result)

                    age                                              \
income         -1          20000      30000      40000      50000
sex age
f   (10, 30]  25.553221  23.955607  25.694737  26.613497  26.990826
    (30, 60]  39.332314  38.994083  38.491667  38.668675  40.000000
    (60, 80]  63.763098  65.166667  64.500000  64.500000  64.100000
m   (10, 30]  25.808065  24.068049  25.736287  26.049869  26.482650
    (30, 60]  38.722462  37.874659  39.170732  37.536232  39.577039
    (60, 80]  63.954407  64.818182  64.500000  63.777778  64.500000

                                                                     ...  \
income          60000      70000      80000      100000     150000   ...
sex age                                                              ...
f   (10, 30]  27.046875  25.902439  27.500000  27.906250  27.166667  ...
    (30, 60]  39.839161  42.982906  41.415385  41.455814  40.406780  ...
    (60, 80]  64.285714  64.375000  63.250000  64.444444  65.000000  ...
m   (10, 30]  26.557692  26.705394  26.545977  27.298701  27.460317  ...
    (30, 60]  39.016000  39.816327  39.917012  39.550114  39.659524  ...
    (60, 80]  64.000000  64.000000  63.550000  63.680000  63.800000  ...

                 height                                              \
income          40000      50000      60000      70000      80000
sex age
f   (10, 30]  65.319018  64.880734  65.343750  65.121951  65.759259
    (30, 60]  65.656627  65.088542  65.209790  65.282051  65.179487
    (60, 80]  65.900000  65.000000  64.857143  65.125000  65.000000
m   (10, 30]  70.425197  70.328076  70.738462  70.473029  70.609195
    (30, 60]  69.971014  70.456193  70.548000  70.585034  70.373444
    (60, 80]  70.555556  70.000000  69.600000  71.000000  71.500000


income          100000     150000     250000     500000     1000000
sex age
f   (10, 30]  65.000000  67.833333  72.000000  68.000000  66.190476
    (30, 60]  65.251163  66.288136  64.666667  66.000000  65.682927
    (60, 80]  64.333333  63.750000        NaN        NaN        NaN
m   (10, 30]  70.558442  70.841270  70.707317  71.391304  70.599222
    (30, 60]  70.775626  70.676190  71.382353  71.636364  71.000000
    (60, 80]  70.680000  71.100000  72.000000        NaN  69.000000

[6 rows x 26 columns]